imagewriter.cpp

Append "rpi-imager/version-num" to the default User-Agent when curl is downloading the image so that image hosts can more easily distinguish rpi-imager traffic from other traffic.

Fix #62 (custom user-agent)

---

CMakeLists.txt

Use of `share/pixmaps` is deprecated in favour of `share/icons` with right subfolder depending on the size of the icon (here 128x128). Best would be to provide the icon as an SVG and not worry about sizes depending on the desktop environment.

Install icon under share/icons

---

CMakeLists.txt
mac/Info.plist

Fixes #13 
Specify an NSPrincipalClass in Info.plist to enable Retina display support
The default Info.plist template provided by CMake doesn't have this key, and
CMake only has minimal support for settingstypically found in this file.
In order to specify NSPrincipalClass, we need to provide the whole Info.plist instead.
Info.plist is also specified as a dependancy to the application so that it will
appear in the project explorer, and changes to this file will trigger a rebuild. 
Before | After
---|---

Fix for #13 Fuzzy text on macOS Retina Displays

---

CMakeLists.txt
linux/rpi-imager.metainfo.xml

I intend to submit a Flatpak for rpi-imager to [Flathub](https://flathub.org/) (I have it working locally) and need to provide some [AppStream](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html) metadata for proper registration in Linux software stores like GNOME Software or KDE Discover.
I prefer contributing these metadata upstream so that all downstream distributions can benefit (not only Flatpak). I am proposing `org.raspberrypi.rpi-imager` as the application ID but it can be something else, as long as the latter fulfills the requirements explained in [section 2.1.3](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent).
I used the wording in the blog post introducing the imager for the description. Feel …

Appstream metadata

---

CMakeLists.txt
i18n/rpi-imager_de.ts
i18n/rpi-imager_fr.ts
i18n/rpi-imager_nl.ts
i18n/rpi-imager_tr.ts
i18n/rpi-imager_zh_cn.ts
i18n/translations.qrc

Two things are not translated because I don't own the OS to check the translation:
Windows
**Controlled Folder Access** seems to be enabled. Please add both rpi-imager.exe and fat32format.exe to the list of allowed apps and try again.
macOS
Please verify if 'Raspberry Pi Imager' is allowed access to **'removable volumes'** in **privacy settings** (under **'files and folders'** or alternatively give it **'full disk access'**).
I could translate those, but I'm not sure if they match the real name in the OS.

Add German translation

---

README.md

- The new wording has the advantage that it specifies which platforms the binaries are for - we probably don't want to get folks hopes up that their potentially unsupported platform is supported by our binaries
- Give instructions for how to get it on Raspberry Pi OS - no need to visit download page - it just needs a single shell command

README.md: Improve wording on download link, add how to get on Raspberry Pi OS

---

README.md

As introduced in 95ce718d41d117b2f29696b02baeda715c944071, document the telemetry sent to https://rpi-imager-stats.raspberrypi.org, why it is collected, what is collected, how long it is stored for and how to opt-out.

Document telemetry and how to opt-out

---

README.md

In order to view the impact of changes such as OS releases over a longer period of time, we have removed the automatic expiry of the anonymous download counts from the rpi-imager stats service.
For reference, the download counts contain only the following data:
> ZREVRANGE image:2021-03-12 0 1 WITHSCORES
1) Raspberry Pi OS (32-bit)
2) 1234
3) Raspberry Pi OS Lite (32-bit)
4) 567
Update the README section about telemetry in order to reflect the change.

Remove download count retention period from README

---

README.md
config.h

Now we've moved the downloads page and telemetry endpoint from raspberrypi.org to raspberrypi.com, update the download link in the README and the URL used for telemetry. (Note that the raspberrypi.org endpoint will continue to work indefinitely in order to support existing clients.)

Update URLs after move to raspberrypi.com

---

src/imagewriter.cpp

I have automatically generated images that do not match *.* as filename contains no dots. I have to rename them every time.

Allow selection of files without extension

---

src/dependencies/mountutils/src/linux/functions.cpp
src/downloadextractthread.cpp
src/downloadthread.cpp
src/linux/linuxdrivelist.cpp
src/linux/udisks2api.cpp

See: `rpi-imager/src/downloadthread.cpp:1015:14: warning: Missing reference in range-for with non trivial type (QByteArray) [clazy-range-loop]`

code-quality: fixed all range-loop warnings which were reported from clazy

---

src/dependencies/drivelist/src/drivelist.hpp

Hello I was working on to compile latest version of rpi-imager via gcc13 and clang 15 and I encountered this error
```sh
In file included from XXXXX/rpi-imager/src/linux/linuxdrivelist.cpp:6:
XXXXX/rpi-imager/src/linux/../dependencies/drivelist/src/drivelist.hpp:42:3: error: ‘uint64_t’ does not name a type
42 |   uint64_t size;
|   ^~~~~~~~
XXXXX/rpi-imager/src/linux/../dependencies/drivelist/src/drivelist.hpp:22:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
21 | #include <string>
+++ |+#include <cstdint>
22 | #include <vector>
XXXXX/rpi-imager/src/linux/../dependencies/drivelist/src/drivelist.hpp:43:3: error: ‘uint32_t’ does not name a type
43 |   uint32_t blockSize = 512;
|   ^~~~~~~~ …
```

fix: header import cstdint

---

src/linux/linuxdrivelist.cpp

Possible hotfix for updated version of lsblk on Arch based distributions.
See issue #610.

Hotfix for Issue #610

---

.gitignore

While building with CMake and VSCode, I noticed we were not ignoring temporaries and ide-specific configuration.
Add both the default CMake build directory and the vscode private directory to a .gitignore.
This should really be considered a starting point rather than a destination - I fully expect this list to grow as I sound out
the other builds.

gitignore: Ignore CMake, vscode artefacts.

---

README.md

Our CMakeLists will look for lzma, and will fail by default if lzma is not found.
As a response, add lzma development packages to the Fedora and Ubuntu/Debian README sections.
Confirmed this lets CMake configure with default options on WSL2/Ubuntu.

Add lzma dependencies to instructions

---

.gitignore

Ignore two additional patterns to capture debuild intermediates and results.

gitignore: Ignore debuild artefacts

---

src/linux/rpi-imager.desktop

Add " %F" to the Exec parameter in the rpi-imager.desktop file so that Linux desktop environments know that rpi-imager can be used to open files.  After this change, Imager appears within the list of "Open With" applications in GNOME, and you can set it so double-clicking image files always opens rpi-imager.

Enable file associations on linux

---

src/main.qml

If you load a custom image by running `rpi-imager my_image.img.xz` then the Advanced Options button is not shown.  This is triggered if you set a file association to load rpi-imager and then double-click an image file.
The fix is simply to set the visibility on this button on start-up (custom images set on the command-line are loaded before this).
Fixes #451

Show options when opening image by file association

---

README.md
src/OptionsPopup.qml
src/UseSavedSettingsPopup.qml
src/i18n/rpi-imager_ca.ts
src/i18n/rpi-imager_de.ts
src/i18n/rpi-imager_en.ts
src/i18n/rpi-imager_es.ts
src/i18n/rpi-imager_fr.ts
src/i18n/rpi-imager_it.ts
src/i18n/rpi-imager_ja.ts
src/i18n/rpi-imager_ko.ts
src/i18n/rpi-imager_nl.ts
src/i18n/rpi-imager_ru.ts
src/i18n/rpi-imager_sk.ts
src/i18n/rpi-imager_sl.ts
src/i18n/rpi-imager_tr.ts
src/i18n/rpi-imager_uk.ts
src/i18n/rpi-imager_zh.ts

This reverts commit 2fb58dc01c1159f1ea11b056f086e9fc21c5c281.
The original commit included an unexpected deletion of _all_ translations in certain languages. This was unintented, and appears to have been a merging artefact.
This change will be re-submitted as a separate PR.

Revert "i18n: Advanced Settings -> OS Customisation"

---

README.md

Without this, the cmake step fails with "cmake error: could NOT find LibLZMA".

fix: add xz-devel to fedora build dependency installation instructions

---

src/main.qml

Seems like there's a weird Qt bug in the ProgressBar widget where giving it padding means the white progress indicator doesn't actually start at the left edge of the bar or extend to the right edge of the bar.  So just remove the padding from ProgressBar because it's not doing much.
Before: 
After:

Remove padding from progress bar

---

embedded/imager/package/rpi-imager/0001-rpi-imager-change-window-to-popup.patch
embedded/imager/package/rpi-imager/rpi-imager.mk

When using local site, buildroot does not automatically apply patches. The buildroot manual recommends using the POST_RSYNC hook to apply patches if needed, so implement this to automatically apply patches.
Resolves #671

Embedded: Automatically apply patches

---

README.md
embedded/imager/package/rpi-imager/0001-rpi-imager-change-window-to-popup.patch
src/OptionsPopup.qml
src/UseSavedSettingsPopup.qml
src/i18n/rpi-imager_ca.ts
src/i18n/rpi-imager_de.ts
src/i18n/rpi-imager_en.ts
src/i18n/rpi-imager_es.ts
src/i18n/rpi-imager_fr.ts
src/i18n/rpi-imager_it.ts
src/i18n/rpi-imager_ja.ts
src/i18n/rpi-imager_ko.ts
src/i18n/rpi-imager_nl.ts
src/i18n/rpi-imager_ru.ts
src/i18n/rpi-imager_sk.ts
src/i18n/rpi-imager_sl.ts
src/i18n/rpi-imager_tr.ts
src/i18n/rpi-imager_uk.ts
src/i18n/rpi-imager_zh.ts
src/imagewriter.cpp
src/main.qml

In the new flow, it doesn't make sense to _not_ save the OS
customization parameters, so remove the ComboBox.
Additionally, our data model was failing to notify the UI of changes to
the saved settings state. Due to time constraints, I'm not able to
resolve the binding in the 'correct' manner, but I can introduce a
makeshift status signalling mechanism to prevent UI inconsistency

OS customization rebrand, consistency

---

src/UseSavedSettingsPopup.qml
src/main.qml

Previously, if you clicked "edit settings" in the "use customisation" msgbox then the flow got a bit confusing, when you saved settings the "use customisation" msgbox would have disappeared and you had to click "next" and go back through again.  Instead, keep the "use customisation" msgbox open when editing settings so when you save settings you are back where you left it.
Also:
- Make "use customisation" modal so you can't click other things while it's open
- Separate windows in QtQuick can't be modal so we can't stop the user interacting with the main window while "edit settings" is open.  This could get confusing, so if they close the "use customisation" modal in the main window then close the settings window.
- Fix a bug where saved settings weren't recognised on startup, only after …

Don't hide "use customization" msgbox when editing settings

---

embedded/imager/package/rpi-imager/0001-rpi-imager-change-window-to-popup.patch
src/main.qml

- Make write confirmation popup modal
- Force focus on the write confirmation popup when it opens
- Force focus on the error popup when it opens
- When the hw select popup opens, force focus on the ListView instead of on the currentItem, because the latter doesn't work when the list is empty.
- On embedded, when the settings popup closes, force focus back to the usecustomisation dialog

Fix various keyboard focus issues

---

src/i18n/rpi-imager_ca.ts
src/i18n/rpi-imager_de.ts
src/i18n/rpi-imager_en.ts
src/i18n/rpi-imager_es.ts
src/i18n/rpi-imager_fr.ts
src/i18n/rpi-imager_it.ts
src/i18n/rpi-imager_ja.ts
src/i18n/rpi-imager_ko.ts
src/i18n/rpi-imager_nl.ts
src/i18n/rpi-imager_ru.ts
src/i18n/rpi-imager_sk.ts
src/i18n/rpi-imager_sl.ts
src/i18n/rpi-imager_tr.ts
src/i18n/rpi-imager_uk.ts
src/i18n/rpi-imager_zh.ts

As part of changing the reference string, these translations will require a rework.
Without this change, any translations would use both the wrong string _and_ fail to get relfected in the UI.

i18n: Remove broken translations

---

src/MsgPopup.qml
src/OptionsPopup.qml
src/UseSavedSettingsPopup.qml
src/main.qml
src/qml.qrc
src/qmlcomponents/ImButton.qml
src/qmlcomponents/ImButtonRed.qml

- All of our red buttons were ImButton with the colours overridden at the use site.  Instead make an ImButtonRed which defines these colours in one place.
- Previously the red buttons had focus indicated by the text colour changing from white to blue.  This was quite hard to see, instead change the button colour to blue (as is done for the white buttons). A darker shade of blue is used so that there is still good contrast with the white text.
- Update the reds (buttons and main screen background) with the branding-approved red: the official colour palette says Pi Red is #cd2355
Old button focus (text colour):
New button focus (background colour):

Improve red button focus colour

---

src/OptionsPopup.qml

With the move from OS customisation being a popup to being a separate window, it is no longer closed by the escape key.  Add a handler to restore this behaviour.

Make escape key close OS customisation window

---

src/main.qml

When filtering the OS list, if all items in a category/sublist are filtered out then don't show the category/sublist.
Also, clear the selected OS when the HW device is changed, otherwise you can get weird effects like having an incompatible (hw, os) pair selected or the highlighted OS moving when the items in the OS list change.

Hide empty categories when filtering

---

src/main.qml

We're going to take advantage of the convention of always putting the recommended OS first in the list, and append "(Recommended)" to it's description.
This moves the recommendation out of the JSON, and makes the recommendation durable to filtering.

qml: Recommend the 'top' OS

---

src/config.h

In order to ensure the 'Recommended' tag shows up for older versions of the Imager, we should migrate to using V4 for the version where we move the tag out of the JSON file.

config: Use ImageList v4

---

src/main.cpp

This is a compromised change. Essentially, I'm working around a poorly-understood failure mode in Qt5, where the disk cache can occasionally fail to invalidate, resulting in stale compiled units being used.
This will increase application start times in favour of correctness.
Likely to resolve #707

qml: Disable disk cache entirely

---

src/downloadthread.cpp

Currently you can configure cloudinit-userdata and cloudinit-networkconfig via the CLI, however due to a check around the customizeImage call it would never be applied.

Also customize image if only a cloudinit payload exists

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

We'll set assignees when actually working on issues instead of having every issue assigned when created.

Remove default asignees from issue templates

---

src/OptionsPopup.qml

It is possible to connect to open wifi networks using raspi-config or the wf-panel-pi GUI.  It was also possible in rpi-imager but only with a workaround - if you entered a dummy PSK it would be ignored if the SSID was that of an open network.  (This also meant a Pi could be tricked into connecting to an open network on first boot even if a PSK was configured).
The change in https://github.com/RPi-Distro/raspberrypi-sys-mods/pull/83 has a side effect which means that Pis will no longer connect to an open network if a PSK is configured.
This commit lets the user enter no PSK to indicate that an open network should be configured.

Allow no PSK to be entered for open wifi

---

src/imagewriter.cpp
src/imagewriter.h
src/main.cpp
src/main.qml

- Simple implementation of OS list fetching in backend
- Replace frontend OS list fetching by calls to backend
- OS list updates are brought in asynchronously, avoiding excessive UI blockage.
- "Erase" and "Custom" OS list options are always present, even in a no-internet scenario
Based-On: cillian64/rpi-imager/oslist_backend
Resolves #714

qml: move OS list fetch to backend

---

src/imagewriter.cpp

Since #719, you can no longer use a local json file with --repo (At least in Qt 6). A network request to a file:// url has statusCode 0, which caused this check to fail previously.

Fix file being passed to --repo

---

src/i18n/rpi-imager_ja.ts

The original translation is correct, but this can be made better.
For your reference, I am attaching the number of results from the search with the original wording and my wording. It is one reference.
---

i18n: Japanese minor wording corrections

---

src/OptionsPopup.qml

Resolves #739 by constaining the size of the username field to match the limit imposed by systemd, and the hostname to the limit specified on man7.

qml: Impose limits on usernames, hostnames

---

src/OptionsPopup.qml

Using onTextEdited meant that the clear() call would happen after the edit had actually happened.
Instead, use the Keys.onPressed handler, which happens earlier in the input chain.
Resolves #531

qml: Clear saved password using onPressed handler

---

src/linux/rpi-imager.metainfo.xml.in

launchable desktop-id type was no longer matching after 06abbadbb501869c29076df0f0409b977869e992 causing appstream-builder to fail to generate appdata for this package.

appstream metainfo: Fix appstream-builder generation

---

src/i18n/rpi-imager_ca.ts
src/i18n/rpi-imager_de.ts
src/i18n/rpi-imager_en.ts
src/i18n/rpi-imager_es.ts
src/i18n/rpi-imager_fr.ts
src/i18n/rpi-imager_it.ts
src/i18n/rpi-imager_ja.ts
src/i18n/rpi-imager_ko.ts
src/i18n/rpi-imager_nl.ts
src/i18n/rpi-imager_pl.ts
src/i18n/rpi-imager_ru.ts
src/i18n/rpi-imager_tr.ts
src/i18n/rpi-imager_uk.ts
src/i18n/rpi-imager_zh-TW.ts
src/i18n/rpi-imager_zh.ts
src/main.qml

Looks like I will need to learn qt/qml for work, thought I could start by contributing some small enhancements to rpi-imager.
https://github.com/raspberrypi/rpi-imager/assets/32407/78de5e3b-0b8a-444c-aa22-9c9084588a45
I updated the message to say "No storage devices found" instead of 'nothing to see here'

Add a message when there are no storage devices. Fixes #798

---

src/i18n/rpi-imager_it.ts

@maxnet 
Please merge. Thanks.

Update Italian language

---

src/CMakeLists.txt
src/config.h

Makes the filtering-behaviour userconfigureable during compile-time. This way its easier to configure the imager for flashing SATA or NVME Drives installed in your system (because of lack of adapters), or if the drives are (accidentally) labled as systemdrives by drivelist.
By default system drives are still filtered.
Fixes #534

Exposing 'DRIVELIST_FILTER_SYSTEM_DRIVES' as a cmake variable

---

src/cli.cpp

Add a new CLI flag, `--disable-eject`, which maps to the option in the UI to not automatically eject the storage media after writing.
While we're here, use a more concise declaration form for the cli options.
Resolves #851

cli: Add disable-eject

---

src/timezones.txt

Currently the timezone setting for Kyiv is spelled as `Europe/Kiev`. This is incorrect as the official spelling is `Kyiv`, more info can be found [here](https://en.wikipedia.org/wiki/KyivNotKiev). This PR corrects the spelling.
Thank you.

Corrected the spelling for Kyiv

---

src/linux/linuxdrivelist.cpp

On systems with a very large number of snap packages installed (for example), there are a considerable number of loop devices. In this case, the `lsblk` command in `linuxdrivelist` fills the stdout pipe, blocks, and the rpi-imager process assumes it has timed out [1].
This PR is a trivial work-around that simply excludes loop devices (major=7) from the `lsblk` output. Given subsequent code [2] excludes everything starting with `/dev/loop` anyway, there should be no change in user experience with this exclusion other than rpi-imager not failing on such systems (with a very large number of loop devices).
However, it may be preferable to fix the call to `lsblk` so that it doesn't (potentially) block the main UI thread for up to two seconds and die when the `lsblk` output is sufficiently …

Fix timeout on systems with large numbers of loops

---

src/OptionsPopup.qml

On modern Debian and Ubuntu releases (23.10 onwards for Ubuntu), `localectl` does not (currently) operate [1] [2]. The `keyboard:` section should be used instead, which should do the right thing on whatever platform cloud-init is being used on (writes `/etc/default/keyboard` on Debian/Ubuntu, uses `localectl` on RHEL/Fedora, runs `setup-keymap` on Alpine).
[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038762
[2]: https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/2030788

localectl doesn't work on modern Debian/Ubuntu

---

src/i18n/rpi-imager_zh.ts
src/linux/org.raspberrypi.rpi-imager.desktop

Update zh-CN (Simplified Chinese) translation.
- The Simplified Chinese translation of Raspberry Pi Imager has been revised to more closely align with the original text.
- Any entries that were not present in the original text have been removed, and any entries that were not translated have been updated.
- The translation has been subjected to rigorous accuracy checks to ensure optimal alignment with the target audience of Raspberry Pi.
- The terminology employed in reference to Apple macOS has been aligned with the Simplified Chinese translations utilized within the macOS system itself.
- Added translation for Linux desktop icon file
Note: I am unfamiliar with the programming environment on macOS and the process of modifying `Info.plist.in`.  **Therefore, I request that someone with the …

Update zh-CN (Simplified Chinese) translation

---

src/devicewrapper.cpp

gpt.Signature is not a null-terminated string, but an 8-byte character array. Using `strcmp` will not provide a valid result. Use `strncmp` over the first 8 bytes instead.

Fix GPT signature test

---

src/downloadthread.cpp

This if() condition checks the result of seek, write, flush and fsync. The first three are methods on QFile, so return a truthy value on success. write() returns number of bytes written while seek() and flush() return bool true on success. Therefore they have to be inverted to detect errors. However, fsync() is a posix system call, so it returns zero (false) on success. Therefore it should not be inverted.
Note that currently this entire code block can never run. knownsize is always zero because QFile.size() currently cannot determine the size of a block device. However, when I asked to confirm this behavior, a Qt maintainer decided to implement it, so there is now a PR. If that is released then this code block will become live and the reversed fsync check will cause a problem.
PR: …

Linux/OSX: Fix reversed fsync check

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

The issue templates had not been adjusted for the latest release, fix this by inserting the correct version into the template. In the future this is a task that should probably be automated.

Update the issue templates for the latest release

---

src/linux/linuxdrivelist.cpp

After trimming the lsblk output by listing only required columns (see [1]), the output includes not only the disk devices, but also their partitions, which significantly clutters the device selection dialog.
This happens becuase the "--output" argument [2] defaults to using "--tree", but only if the column "NAME" is outputed, which in current state doesn't (only "kname" is used). So that all child elements (e.g. partitions) are listed on the same level with disk devices.
Thus ist's proposed to explicitly add "--tree" argument, so that we don't rely on lsblk CLI intricacies.
Fixes #935 
[1] https://github.com/raspberrypi/rpi-imager/commit/baae3c76417cde5c7a38b37400a016f7e7cdb5d1
[2] https://www.mankier.com/8/lsblk#--output

Explicitly add '--tree' to the lsblk to remove partitions from top level output

---

src/CMakeLists.txt

Use the IMAGER_SIGNED_APP flag we use on macOS to control Windows signing, too.
This means that Windows developer builds can be made without access to the signing key, and without manually hacking the root CMakeLists

cmake: Build Windows binary unsigned by default

---

src/CMakeLists.txt
src/drivelistitem.cpp
src/drivelistitem.h
src/drivelistmodel.cpp
src/drivelistmodel.h
src/main.qml

Rather than using a compile-time variable to determine when to filter system drives, introduce a UI item to allow users to dynamically grey-enable system drives.
This change carries the risk that users might decide to destroy their PC's hard drive. The mitigation has been to retain the behaviour of filtering by default - this change only moves the point of choice on filtering to the UI.
This change will be most beneficial in the Network Installer, where attached NVMe or USB drives may incorrectly be flagged as 'system' drives.

Filter system drives by user choice

---

appimagecraft.yml

The Wayland composition flags in the Qt AppImage support are not safe to use - they include a system-owned copy of libwayland-client that is cross-called by the system Mesa - outside of the AppImage. Including the system-owned copy from the build host creates an ABI breakage that prevents execution.
This is an unacceptable situation, and until a more precise fix can be provided, disable Wayland client support in Imager.
Fixes #942

AppImage: Disable Wayland support

---

src/imagewriter.cpp

Use the blconfig alias to find the correct nvmem device to read the bootloader configuration, the practical effect being that IMAGER_REPO_URL should work on Raspberry Pi 5.
Fixes #894

embedded: Use blconfig alias to find bootloader config

---

.github/ISSUE_TEMPLATE/bug-report.yml

fix: typo in Github issue template

---

src/devicewrapperfatpartition.cpp

Improvements regarding comments in https://github.com/raspberrypi/rpi-imager/issues/988

Revert unnecessary changes to calculating the sizes of longFilename

---

src/i18n/rpi-imager_zh-TW.ts

This pull request includes several updates to the Traditional Chinese translations in the `src/i18n/rpi-imager_zh-TW.ts` file. The changes primarily focus on updating the translation, improving its accuracy, and removing outdated or unused translation entries.

Update and improve zh-TW Traditional Chinese locale

---

src/windows/rpi-imager.nsi.in

- make NSIS(windows installer) use the "all users" shell folder
- that makes the shortcut be created for all users instead of only the admin user that installed the application

make NSIS(windows installer) use the "all users" shell folder - fix app shortcut for all users

---

src/imagewriter.cpp

The debug output refers to it as "firstuse.sh" instead of "firstrun.sh" like everywhere else. I could not find any other references to this string, so I am assuming its a mistake.

fix typo in debug output for firstrun.sh

---

src/CMakeLists.txt

To avoid unnecessary churn as we iterate the application, get this programmatically.

macOS: Programmatically get copyright year.

---

src/imagewriter.cpp
src/windows/rpi-imager.nsi.in

Hi there,
I love using the Raspberry Pi Imager, but I noticed one small detail when using it with Yocto built .wic images. Every time I'm trying to flash a .wic image, I have to change the file extensions to "All Files" which can be a bit cumbersome. Therefore I added the .wic file format to the list of default extensions.
I hope this makes sense and helps folks like me that experiment or work with Yocto.
Please let me know if there are any issues that I might have overlooked.
Kind Regards,
sohnemann

Added .wic as a file format for Yocto builds

---

src/i18n/rpi-imager_ca.ts
src/i18n/rpi-imager_de.ts
src/i18n/rpi-imager_en.ts
src/i18n/rpi-imager_es.ts
src/i18n/rpi-imager_fr.ts
src/i18n/rpi-imager_he.ts
src/i18n/rpi-imager_it.ts
src/i18n/rpi-imager_ja.ts
src/i18n/rpi-imager_ka.ts
src/i18n/rpi-imager_ko.ts
src/i18n/rpi-imager_nl.ts
src/i18n/rpi-imager_pl.ts
src/i18n/rpi-imager_pt.ts
src/i18n/rpi-imager_ru.ts
src/i18n/rpi-imager_sk.ts
src/i18n/rpi-imager_sl.ts
src/i18n/rpi-imager_tr.ts
src/i18n/rpi-imager_uk.ts
src/i18n/rpi-imager_zh-TW.ts
src/i18n/rpi-imager_zh.ts

This change brings the reference strings up to date, notably catching an incorrect SSH key help text

lupdate: Update translation reference strings

---

.github/ISSUE_TEMPLATE/bug-report.yml

I assume that 500, and Compute Modules 5 were unintentionally forgotten.
The Raspberry Pi 2B is of course an old model, but some users (like me) still use it.
I don't remember if there were other variants of the Raspberry Pi 2, please correct me if I missed something.
Off topic, but I wonder if the future Raspberry Pi OS (Debian 13, Trixie) will still support the 32-bit architecture and therefore the Raspberry Pi 2?

Updating the list of Pi models when creating a bug

---

src/MainPopupBase.qml
src/main.qml
src/qmlcomponents/ImButton.qml
src/qmlcomponents/ImButtonRed.qml
src/qmlcomponents/ImPopup.qml

Material Theme does not work on embedded mode. Have changed buttons and pop-ups to be drawn without Material. 
Visually the same as the desktop imager (Apart from the main screen button's hover effect does not seem to work - however this is not critical at this stage!)

Visual Fixes for Embedded Imager

---

src/i18n/rpi-imager_pl.ts

I did everything, but I needed to make some workarounds.
The window is too thin for some texts in Polish as Polish language is more descriptive than English, even though I tried to minimize unneeded words. I think we could make the window a bit wider and use more `<br>` elements for these small captions under inputs.
Examples below:
---
"Pomiń dostosowywanie" as "skip customization":
The button is the only culprit for extending input's width.
"Pomiń" as "skip":
---
The input's text is too long.
I went with solution below. I think it was too descriptive anyway, because it should be enough for user to tell him "insert key" and the next thing is a button with "browse" instead of descriptive (repetitive) input text. (knowledge from my frontend journey).
---
Moreover, the "Customization: …

feat: translate to Polish
