raspberrypi/rpi-imager

- i18n/rpi-imager_tr.ts
Hi there.
I started localizing Turkish for image writer. I started translating en.ts file with reference. I'll let you know when all translations are finished
> Turkish translations done

- CMakeLists.txt
- i18n/rpi-imager_it.ts
- i18n/translations.qrc
@maxnet 
Add language file for Italian GUI
Make some changes to add Italian language to the list of available languages.
Please check and merge.
Please add also Slovak translation (https://github.com/raspberrypi/rpi-imager/pull/116)
If you can please release a new application version (the current 1.4 i s mono language = English) to test multilanguage UI.
> Add Italian translation

- i18n/rpi-imager_it.ts
@maxnet 
Please check and merge. Thanks.
> Update Italian language

- windows/rpi-imager.nsi.in
@maxnet 
Update one string for Italian in NSIS installer script.
Please check and merge. Thanks.
> Update Italian string for installer

- i18n/rpi-imager_it.ts
Fix typos and correct language attribute
> Update Italian translation

- i18n/rpi-imager_de.ts
- i18n/rpi-imager_en.ts
- i18n/rpi-imager_fr.ts
- i18n/rpi-imager_it.ts
- i18n/rpi-imager_nl.ts
- i18n/rpi-imager_sk.ts
- i18n/rpi-imager_tr.ts
- i18n/rpi-imager_zh_cn.ts
- main.qml
Hello,
Thanks you for Raspberry Pi :heart: I find rpi-image very well done.
I propose to change `SD card` description to `Storage` as we can choose also an USB storage.
What do you think ?
> Change SD Card description

- i18n/rpi-imager_zh_cn.ts
#166
update Chinese translation file
> update Chinese translation

- i18n/rpi-imager_zh_cn.ts
fix & update Chinese translations
> fix & update Chinese translations

- i18n/rpi-imager_de.ts
I forgot to submit a PR ealier, but here's another improvement PR.
> Fix a few mistakes in the German translation

- CMakeLists.txt
- i18n/rpi-imager_sl.ts
- i18n/translations.qrc
> Add sl-SI (EU/Slovenija) translation

- src/CMakeLists.txt
- src/config.h
- src/imagewriter.cpp
- src/main.qml
When included in a distribution as package some settings may make sense to turn off.
> Add compile time options for telemetry and updates

- src/i18n/rpi-imager_ko.ts
-Fix sentence
-Translate remaining untranslated
-Update wireless LAN words
> Rpi-imager_ko : some copy-edit

- debian/rpi-imager.manpages
- doc/man/rpi-imager.1
Just adds a basic man-page covering the GUI and cli functionality
> Add a man-page for rpi-imager

- src/windows/rpi-imager.nsi.in
@maxnet 
It's useful to check in any window of instalelr whick is the evrsion that yoiur are installing.
I aded also the info for Product version (currently missing) in installer exe file properties.
Please check and merge.
> Add on top left after progran name program version

- src/i18n/rpi-imager_ko.ts
Add message for 'unmounting drive'.
> rpi-imager_ko: add message for 'unmounting drive'

- src/i18n/rpi-imager_ca.ts
Removed "vanished" translations, added the new ones, and fixed some minor issues for the Catalan language file.
Thank you!
> Update Catalan translation files

- src/main.qml
Fixes https://github.com/raspberrypi/rpi-imager/issues/620
First time with qml, seems to work.
> feat: Allow image drag/drop

- src/i18n/rpi-imager_ja.ts
* Translated all unfinished sentences.
* Fixed confusing translations.
* Fixed minor translation errors.
> Improve Japanese translations

- src/i18n/rpi-imager_de.ts
as requested here https://github.com/raspberrypi/rpi-imager/pull/645#issuecomment-1759644057
added new translations and cleaned up some exisiting ones too
> Update German translations

- src/i18n/rpi-imager_es.ts
> Update Spanish translation

- src/i18n/rpi-imager_ko.ts
- See https://github.com/raspberrypi/rpi-imager/pull/645
> some update korean translation

- src/CMakeLists.txt
- src/i18n/rpi-imager_zh-TW.ts
- src/i18n/translations.qrc
> Add zh-TW Traditional Chinese translation

- src/i18n/rpi-imager_de.ts
... after seeing 1.8.1 in action I thought of making some translation clearer
> Update german translation

- README.md
In order to assist users of the tool, provide a direct link to the official Raspberry Pi documentation for Raspberry Pi Imager.
> Link to official docs from README

- src/i18n/rpi-imager_pl.ts
- src/i18n/translations.qrc
> Added Polish translation

- src/OptionsPopup.qml
Import the systemd recommended username validation regex.
Resolves a ticket reported to the Raspberry Pi information inbox.
> OS Customisation: Validate usernames

- src/i18n/rpi-imager_zh.ts
Correcting a few minor errors.
> Correcting a few minor errors in zh-CN (Simplified Chinese) translation

- src/i18n/rpi-imager_ca.ts
- src/i18n/rpi-imager_es.ts
Catalan and Spanish translation update: Remove vanished entries, translate missing, and fix some minor issues.
If everything is okay, please merge when you have time.
Thank you!
> Update Catalan and Spanish translations

- src/CMakeLists.txt
- src/i18n/rpi-imager_he.ts
- src/i18n/translations.qrc
Translated using Lokalize, finalized with Qt Linguist.
> Added Hebrew translation

- src/windows/rpi-imager.nsi.in
fixes #952
https://nsis.sourceforge.io/Add_uninstall_information_to_Add/Remove_Programs#Recommended_values
> feat(installer): add quiet uninstall for windows

- src/CMakeLists.txt
- src/i18n/rpi-imager_pt.ts
- src/i18n/translations.qrc
* Add Portuguese translation
* Sort `translations.qrc` file alphabetically
> Added Portuguese translation

- src/i18n/rpi-imager_it.ts
@tdewey-rpi 
Italian language update.
Please merge. Thanks.
> Italian language update

- src/CMakeLists.txt
@tdewey-rpi 
- Remove obsolete strings from .ts language files
- Remove UI references from .ts language files
> Improve Cmakelist.txt

- src/windows/rpi-imager.nsi.in
@tdewey-rpi 
- Add variable for current year
- Add in copyright message the value of current year
- Replace when possible hardcoded text in strings with variables
- Add "installer" as final part of file dscription
- Align first part of varables definitions for a better view/check
Please merge, Thanks.
> Improve Windows installer script

- src/i18n/rpi-imager_it.ts
@tdewey-rpi 
Thanks to @lurch to highlight this.
Please merge. Thanks.
> Fix Italian language issue (empty strings)

- src/CMakeLists.txt
This got squashed in a merge, so bring it back!
> i18n: Re-add _ka translation

- src/imagewriter.cpp
These are largely academic while we use a pre-injestion system that enforces these limits correctly.
However, use of post-increment was not a valid statement. It would copy the pre-increment value of count, and then incremement the copy - resulting in an ineffectual guard.
So instead, just a simpler construct that will create a temporary, which is then copied into the next level.
Additionally, start the count at level 1, not level 0.
> imagewriter: Fixup recursion guards

- src/i18n/rpi-imager_bn.ts
- src/i18n/translations.qrc
Adding Bangla Translations. Also known as Bengali to foreigners.
The translation is complete. Let me know if I missed anything.
Should be displayed as `বাংলা` or `Bangla`, not `Benglai`.
> Bangla Translations

- build-qt.sh
-eglfs & -opengl option parsing fixed, sent to configure instead of CMake
signed-off-by:Ben Benson <ben.benson@raspberrypi.com>
> Fixed configure parsing

- src/i18n/rpi-imager_ru.ts
I hope there won't be any new fields in the near future ;-)
> Translation into Russian for another field

- src/imagewriter.cpp
@lurch - This seems to fix the issue you were seeing with the EEPROM url not being recognised
> Imager Custom EEPROM URL: Fixed

- src/i18n/rpi-imager_bn.ts
- src/i18n/rpi-imager_ca.ts
- src/i18n/rpi-imager_de.ts
- src/i18n/rpi-imager_en.ts
- src/i18n/rpi-imager_es.ts
- src/i18n/rpi-imager_fr.ts
- src/i18n/rpi-imager_ga.ts
- src/i18n/rpi-imager_he.ts
- src/i18n/rpi-imager_hu.ts
- src/i18n/rpi-imager_it.ts
- src/i18n/rpi-imager_ja.ts
- src/i18n/rpi-imager_ka.ts
- src/i18n/rpi-imager_ko.ts
- src/i18n/rpi-imager_nl.ts
- src/i18n/rpi-imager_pl.ts
- src/i18n/rpi-imager_pt.ts
- src/i18n/rpi-imager_ru.ts
- src/i18n/rpi-imager_sk.ts
- src/i18n/rpi-imager_sl.ts
- src/i18n/rpi-imager_tr.ts
- src/i18n/rpi-imager_uk.ts
- src/i18n/rpi-imager_zh-TW.ts
- src/i18n/rpi-imager_zh.ts
Did run `cmake --build . --target rpi-imager_lupdate` as suggested [here](https://github.com/raspberrypi/rpi-imager/pull/1229#issuecomment-3360021163) 
Only some minor changes per language...
> Update translation files
